### ISSUE TITLE
Fix package name of project

### ISSUE THREAD

**Issue by mamadaliev** [Hardelele/chess-bot#1]
Hi, @Hardelele!
Please change package name of your project, from:
```
com.github.hardelele.chess
```
to:
```
com.github.hardelele.chessbot
```

Please do not mark this as spam. Thanks.

**Comment by Hardelele** [comment]
Hallow, @egnaf. 

Thanks, but i think current packege name looks good.

Maybe i will take your advice and change the name of the package later.

Good luck!
